name: Push Docker Image

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'adopt'

    - name: Build with Maven
      run: ./mvnw package

    - name: Build and Push Docker Image
      env:
        REGISTRY: ghcr.io
        IMAGE_NAME: ${{ github.repository }}
        USERNAME: ${{ github.actor }}
        PASSWORD: ${{ secrets.GITHUB_TOKEN }}
      run: |
        # Build the Docker image
        docker build -t $REGISTRY/$IMAGE_NAME .
        
        # Log in to the container registry (GitHub Container Registry)
        echo $PASSWORD | docker login $REGISTRY -u $USERNAME --password-stdin
        
        # Push the Docker image to the registry with the "latest" tag
        docker push $REGISTRY/$IMAGE_NAME:latest