name: Build and Test

on:
  push:
    branches:
      - feature/test-sonarqube

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: 'zulu'

      - name: Build the JAR File
        run: mvn clean package

      - name: Run the Application
        run: java -jar target/*.jar &

      - name: Run Tests
        run: mvn test 