name: Push Docker Image

on:
  push:
    branches: [main]

jobs:
  build-and-push:
    permissions: write-all
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'adopt'

    - name: Build with Maven
      run: ./mvnw package

    - name: Build and Push Docker Image to GHCR
      env:
        REGISTRY: ghcr.io
        IMAGE_NAME: ${{ github.repository }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        IMAGE_NAME=$(echo $IMAGE_NAME | tr '[:upper:]' '[:lower:]')
        docker build -t $REGISTRY/$IMAGE_NAME .
        echo $GITHUB_TOKEN | docker login $REGISTRY -u ${{ github.actor }} --password-stdin
        docker push $REGISTRY/$IMAGE_NAME:latest

  semantic-versioning:
    needs: build-and-push  # Ensure this runs after the build-and-push job
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Fetch all history for semantic-release to work

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm install

    - name: Run Semantic Release
      run: npx semantic-release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}  # If publishing to npm
