name: Push Docker Image

on:
  push:
    branches: [main]

jobs:
  build-and-push:
    permissions: write-all
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Build with Maven
        run: ./mvnw package

      - name: Generate Semantic Version
        id: semantic_version
        run: |
          # Extract version from git tags or calculate next version
          CURRENT_VERSION=$(git describe --tags --abbrev=0 || echo "0.0.0")
          COMMIT_COUNT=$(git rev-list --count HEAD)
          NEW_VERSION=$(echo $CURRENT_VERSION | awk -F. -v OFS=. '{ $NF++; print }')
          echo "CURRENT_VERSION=$CURRENT_VERSION" >> $GITHUB_ENV
          echo "NEW_VERSION=$NEW_VERSION.$COMMIT_COUNT" >> $GITHUB_ENV
          echo "Semantic version generated: $NEW_VERSION"

      - name: Build and Push Docker Image to GHCR
        env:
          REGISTRY: ghcr.io
          IMAGE_NAME: ${{ github.repository }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SEMANTIC_VERSION: ${{ env.NEW_VERSION }}
        run: |
          IMAGE_NAME=$(echo $IMAGE_NAME | tr '[:upper:]' '[:lower:]')
          docker build -t $REGISTRY/$IMAGE_NAME:$SEMANTIC_VERSION .
          docker build -t $REGISTRY/$IMAGE_NAME:latest .
          echo $GITHUB_TOKEN | docker login $REGISTRY -u ${{ github.actor }} --password-stdin
          docker push $REGISTRY/$IMAGE_NAME:$SEMANTIC_VERSION
          docker push $REGISTRY/$IMAGE_NAME:latest

      - name: Push Git Tag for Semantic Version
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git tag ${{ env.NEW_VERSION }}
          git push origin ${{ env.NEW_VERSION }}
